---
title: "The Veg-X standard and the VegX R package"
author: "IAVS Ecoinformatics Working Group"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    css: mystyle.css
vignette: >
  %\VignetteIndexEntry{Veg-X standard documentation}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

## The Veg-X standard

The exchange standard for plot-based vegetation data (Veg-X) is a standard intended to be used for sharing and merging vegetation-plot data of different kinds. It was created by the *Ecoinformatics Working Group* of the **International Association for Vegetation Science (IAVS)** (http://iavs.org) with the to produce a standard specifically for vegetation-plot data that is relatively simple to read and use. To achieve this, highly nested structures were avoided and major vegetation data components were included (e.g. plot attributes, plot observations, organisms) as top-level elements that are referenced by  each other through unique identifiers (e.g. a unique numerical ID) that allow the integrity of the original linkage to be captured. Although the main logical structure of vegetation data (i.e. the logical relationships between major data components) is fixed, alternative, user-defined ways of grouping observations are also allowed. As such, the standard can accommodate projects that are linked across time as well as longitudinal measures of plots or individuals to the extent that these are referenced in the original dataset through appropriate unique identifiers in those original sources.

The standard accommodates different data collection protocols by allowing specific aspects of data collection methods to be captured, such as whether plots were located subjectively or randomly, plot dimensions, definitions of cover-abundance scales, references to published methods, etc. The standard also allows for the original units of measurement to be retained. All elements in the standard are clearly defined. This allows synonymous terms in source datasets to be mapped to a common set of concepts, thus overcoming the problems caused by inconsistent terminologies.

The *plotObservation* is the central Veg-X element, resulting from sampling a physical plot at a specific point in time, and can be related to one or more research projects (Fig. 1). The information about a sampled plot that is fixed over time (e.g. altitude, plot identifier or name, dimensions, aspect, slope, geology) and references to related plots (e.g. a parent plot) are stored in the separate element *plot*. By structuring the plot data in this way, repeat measures and nested plots can be accommodated in the standard. For the top-level element project we adopted the **Ecological Metadata Language** (EML; http://knb.ecoinformatics.org/software/eml/)  project module. EML provides structured, well-defined categories for documenting the key aspects of ecological datasets and is supported by a number of institutions (Jones et al. 2006).

Specific observations, either biotic or abiotic, are components of the plot observation element. The standard allows for observations of vegetation at both the individual specimen (*individualOrganismObservation*) and aggregated organism (*aggregateOrganismObservation*) levels. The standard maintains a clear distinction between the entity of interest (e.g. an individual organism, plot, or stratum) and the observation act (e.g. a measuring event applied to it). Together with unique identifiers that maintain the integrity of references between individual records within each component (e.g. between a plot and all the measuring events applied to it), the separation of components allows the standard to store multiple observations of the same entity (e.g. a plot or a tree). Analogously, a single observation event (e.g. a plot observation) may apply to multiple entities, thereby providing explicit grouping of entity observations. Each entity of interest (e.g. a tree) may have multiple observed properties (e.g. height, dbh) whose values are determined through measurement using a specific procedure or a method belonging to a particular protocol. Unlike individual organism observations, aggregated organism observations do not relate to a specific physical entity but provide estimates of the importance of a (abstract) taxonomic entity within the plot, such as through a cover estimate. Strata can be the subject of stratum observations (e.g. % of tree cover, tree height) and can be linked to aggregated organisms observations (Fig. 1). 

The standard also maintains a distinction between taxonomic identity (the taxon or taxon concept) and how these identities are applied to particular observations of organisms. This is done through three top-level elements: (1) *taxonConcept* is a specific taxonomic concept (i.e. a name–reference combination); (2) *taxonNameUsageConcept* is a particular type of organism referencing one or more individual or aggregate occurrences in one or more plots and typically associated with a taxon name string used by the author of the dataset; (3) *taxonDetermination* is an assertion, made by a party, linking one or more *taxonConcepts* to a *taxonNameUsageConcept.* All the organism observations referencing a given taxonNameUsageConcept are affected by determination events applied to it. This allows different determinations and taxonomic concepts to be associated with a vegetation entity so temporal changes in opinion regarding identification (i.e. "determination history") can be recorded and both formal (i.e. taxon names) and informal (e.g. "field names", "morphospecies") names applied simultaneously to a particular organism observation can be preserved. The fact that the *taxonNameUsageConcept* is not nested within observations permits the same name string to be reused within the scope of the dataset. Community determinations are handled in a similar way: *communityDetermination* elements allow a given plot observation to be related to one or multiple community concepts, although the lack of informal field names removes the need for a *communityNameUsageConcept* entity.

Although the standard supports fully-specified taxonomic concepts, it does not require them. This is important as the full concept is unspecified and furthermore unrecoverable for most legacy data. On the other hand, because the schema can accommodate determination information (who did the identification, when, and with what reference), in theory it could be possible to recover concepts for many legacy datasets – in particular, tropical forest plots where such information is commonly preserved in the form of herbarium voucher specimens.

Veg-X is written as an XML schema, which is a definition of user-defined tags to structure textual information in order to create self-describing datasets. XML (Extensible Markup Language) is an open standard, and XML files are both machine and human-readable (they are stored in plain-text ASCII format). These characteristics help to ensure that data in this format will be accessible in the future. We made use of existing XML schema definitions, which we incorporated as modules of our schema. Specifically, we used parts of the Ecological Metadata Language to define entities like projects or protocols. Similarly, we used TDWG standards such as the Darwin Core geospatial extension (http://wiki.tdwg.org/twiki/bin/view/DarwinCore/GeospatialExtension) to deal with georeferences, and the Taxon Concept Schema (http://www.tdwg.org/standards/117/) for taxon names and concepts. 

## The VegX R package

A barrier with a standard like Veg-X is its complexity, which is nevertheless necessary to accommodate the variety of source data schemes. The large data integration projects employ eco-informaticians to achieve this, but the tools developed are specific to these projects and cannot be readily picked up by others. To make the exchange schema of Veg-X usable by the wider community requires the development of informatics tools for mapping data from different input formats (e.g. relevé tables from different databases, forest inventory data or stem-mapped forest plots) into Veg-X, mechanisms to create unique identifiers to allow source datasets to be combined, and tools to export data from Veg-X to a range of formats that can serve as input to software packages for data analysis and visualisation.  

In 2017, the IAVS *Ecoinformatics Working Group* decided to develop an R package to promote the usage of the Veg-X standard. The R package is specifically intended to be used to:

+ Integrate and harmonize vegetation-plot data from different sources with the aim of conducting new analyses.
+ Produce archivable XML documents with vegetation-plot data coming from new vegetation surveys, without needing the definition of *add hoc* data bases.  

The **VegX R package** currently uses a simplified version of the Veg-X exchange standard, and only a subset of the main elements and sub-elements are included (see next section). This was a practical decision to have a usable tool with a reasonable amount of complexity. Future versions of the package may allow dealing with more elements of the standard.


## Overall structure and main elements of Veg-X (1.6.0)

Veg-X has a non-hierarchical data structure. Different data elements relate to each other via identifiers in a flexible way. The following figure illustrates the relationships between the main elements of Veg-X. 

![Fig. 1. Main VegX elements and their logical relationships. Arrows indicate an identifier of the origin element is referenced in the destination element. Accompanying numbers indicate the number of instances of the origin element that are allowed to be referenced in the destination element. Observations are in tinted boxes. ](LogicalStructure_1.6.0.png) 


The following table provides the description of the main elements of the standard (column 'R' indicates whether the sub-elements are currently implemented in the **VegX R package**):

Main element                   | Description                                     |  R  |
------------------------------ | ----------------------------------------------- | --- |
project                        | Describes the research context in which the dataset was created, including descriptions of over-all motivations and goals, funding, personnel, description of the study area etc. | Yes |
plot                           | A plot is a sampling location. It records the properties of the vegetation plot independent of time and can be referenced by many observations by links to the unique plot code. | Yes |
plotObservation                | Observations made on a single plot and during a single date-time period. This allows all time dependent parameters to be grouped. | Yes |
taxonNameUsageConcept          | A taxon name string occurring within the dataset. This is a usage concept defined by the dataset author which may follow, or be according to, an additional third party. It may be further related to a published name (taxon name, tcs:TaxonName) and or taxonomic name (taxon concept, tcs:TaxonConcept) in taxonDetermination. | Yes |
individualOrganismObservation  | An observation applying to one occurrence of an organism (or part of an organism). It is a container for measurements made on the organism (e.g. diameter, height, crown dimensions, biomass, growth form, number of stems). | Yes |
individualOrganism             | An identified organism recorded during one or more individual organism observation events. Individuals may have an identification label (e.g. tree tag number).| Yes |
aggregatedOrganismObservation  | An observation applying to all occurrences of an organism based on an aggregation factor. |
stratumObservation             | A specific observation applying to a stratum in a single plot during a single date-time period. Each stratum measurement may be referenced by observations of taxa within a plot. For example, abundance estimates of a taxa on a plot within a specific stratum. | Yes |
stratum                        | The specific definition of a stratum referred to by observations in the dataset. A stratum usually belongs to a ordered list that together are the set of strata definitions in use in a specific dataset. | Yes |
siteObservation             | A container for all the site (i.e. soil, climate, landuse, habitat, ...) measurements made on a single plot during a single date-time period. Unlike other observation elements, it relates to *plotObservation* in a one-to-one relationship. | Yes |
surfaceCover | TO BE DONE | No |
surfaceCoverObservation | TO BE DONE | No |
vegetationObservation | TO BE DONE | No |
taxonName                      | A published nomenclatural unit of any rank (order, family, genus, species, subspecies, etc.). Each name is of type tcs:scientificName and may be referenced in taxonDetermination allowing a name usage concept (author name) to be determined or asserted as a specific published nomenclatural name. tcs:scientificName:citation is contained in the literature container. | No |
taxonConcept                   | Representation of a taxon concept. Each taxon concept follows tcs:taxonConcept and may be referenced in taxonDetermination allowing a name usage concept (author name) to be determined or asserted as a specific published taxonomic name/concept. | No |
taxonDetermination             | A specific relationship or assertion between two name concepts which are not part of the original definition of either of these concepts; possibly by a third party. Allows for an author usage concept, i.e. a name string used by the author in this dataset, to be linked to either a published nomenclatural name (taxon name) or a specific taxa treatment (taxon concept), according to a third party. | No |
communityConcept | A name and some kind of definition of a community type, preferably a community name as used in a reference. | No |
communityDetermination | An identification applying one or more CommunityConcepts to a plotObservation by a party.| No |
observationGrouping | An specific grouping of observation records, of any kind, that are grouped in the data management system owing to some common characteristic. | No |


Additional resource elements of the Veg-X schema are used to provide information about people, methods and bibliographic references:

Resource element               | Description                                     |  R |
------------------------------ | ----------------------------------------------- | --- |
party                          | Describes a responsible party (person or organization), and is typically used to name the originator of a resource or metadata document. | No |
attribute                      | A specific definition of a measured property. An attribute has to be one of three types: qualitative (unordered categorical variable, i.e. nominal), ordinal (ordered list of values) or quantitative (a numerical variable, either discrete or continuous. | Yes |
method                         | A specific method definition followed in the creation of the dataset (e.g. the measurement of pH, the estimation of plant abundance or the definition of strata). | Yes |
protocol                       | A specific grouping of methods related by common action. A protocol may have many method or steps.| No |
literatureCitation             | Provides overview information about the literature citation, including title, abstract, keywords, and contacts. | No |



## Details of Veg-X elements and instructions of use

In this section we detail the sub-elements of each main element in the **Veg-X standard**, along with some instructions on how the standard should be used in practice. In the tables describing sub elements, we use column '**#**' to indicate the number of times they can (or must) occur to have a valid Veg-X document ('1' means they occur one and are required; '0..1' means they are optional; '0..n' means they are optional and can occur many times; '1..n' means they should occur at least once, but can occur many times). As before, column '**R**' ('Yes'/'No') indicates whether the sub-elements are currently implemented in the **VegX R package**. In the following, we also indicate when the package restricts the usage of sub-elements.

### Element *project*

A *project* element describes the research context in which the dataset was created, including descriptions of over-all motivations and goals, funding, personnel, description of the study area etc. The definition of Veg-X *project* elements was borrowed from the Ecological Metadata Language (v. 2.0.1). When using the **VegX package**, *project* elements have IDs used for internal consistency, but from the perspective of the users projects are uniquely identified by their sub-element *title*, which occurs only once and is the only sub-element currently recorded.

Sub-element               | Description                                        |  #  |  R  |
------------------------- | -------------------------------------------------- | --- | --- |
title                 | Title of the project.  | 1..n | Yes |
personnel                 | Contact and role information for people involved in the research project. | 1..n | No |
abstract                  | Project abstract.  | 0..1 | No |
funding                   | Funding information. | 0..1 | No |
studyAreaDescription      | Description of the physical area associated with the research project, potentially including coverage, climate, geology, distrubances, etc. | 0..1 | No |
designDescription         | Description of the design of the research project | 0..1 | No |


### Element *plot*

A plot is a sampling location, with or without explicit boundaries. The element *plot* records the properties of the vegetation plot that are independent of time and can be referenced by many observations by links to its ID. While the **Veg-X standard** allows storing globally unique identifiers for *plot* elements, when using the **VegX package** a different set of IDs are used for internal consistency. From the perspective of the user plots are uniquely identified by their sub-element *plotName*. Furthermore, even though the standard allows specifying different kinds of spatial relationships between plots, currently the R package only allows specifying parent-child relationships.

Sub-element               | Description                                        |  #  |  R  |
------------------------- | -------------------------------------------------- | --- | --- |
plotName                 | Name or label for a plot, unique within the data set  | 1 | Yes |
plotUniqueIdentifier     | Plot identifier that is unique across the dataset, derived from the data source, and preferably globally unique. | 0..1 | No |
relatedPlot              | A plot may be related spatially to other plots in order to express parent-child, sub-plot or contiguity. | 0..n | Yes |
location | Information regarding the placement of the plot on earth. | 0..1 | Yes |
geometry | Information regarding the geometry of the plot (area, shape, dimensions, coordinates, ...) as well as the point within the plot that serves as plot origin for location. | 0..1 | No |
topography | Information regarding the shape and features of the surface on which the plot was placed (e.g. aspect, slope, ...). | 0..1 | Yes |
geologicalParentMaterial | Underlying geological material (generally bedrock or a superficial or drift deposit) in which soil horizons form. | 0..n | No |
partyWithRole | The party that undertook the plot placement, and/or parties with other roles. | 0..n | No |

### Element *plotObservation*

An element *plotObservation* is used to group all observations made on a single plot and during a single date-time period. While the **Veg-X standard** allows storing globally unique identifiers for *plotObservation* elements, when using the **VegX package** a different set of IDs are used for internal consistency. From the perspective of the user, plot observations are uniquely identified  by their sub-elements *plotID* (i.e. the plot name) and *obsStartDate*. Furthermore, the VegX package only allows a single (but obligatory) reference to a *project* element.

Sub-element               | Description                                        |  #  |  R  |
------------------------- | -------------------------------------------------- | --- | --- |
plotID                   | A reference to a specific plot by the plot ID       | 1 | Yes |
obsStartDate             | The start date of this specific observation of the plot. Recorded in ISO 8601 date format: yyyy-mm-dd.                   | 1 | Yes |
obsEndDate               | The end date of this specific observation of the plot. Recorded in ISO 8601 date format: yyyy-mm-dd.                   | 0..1 | Yes |
plotObservationUniqueIdentifier     | Plot observation identifier that is unique across the dataset, derived from the data source, and preferably globally unique. | 0..1 | No |
projectID | A reference to a specific 'project'.  | 0..n | Yes |
siteObservationID | A reference to a specific siteObservation by ID. Note that the relationship is one-to-one. Only one siteObservation (with potentially many measurements inside) is allowed for each plotObservation.  | 0..1 | Yes |
previousObservationID | Link to previous plot observations.	| 0..n | No |
partyWithRole | The party that undertook the plot observation and/or other parties with different roles. | 0..n | No |
license | License linked to this plot observation. | 0..1 | No |
taxonomicQuality| Subjective assessment of the taxonomic quality on the plot. | 0..n | No |
observationNarrative | Additional unstructured observations useful for understanding the ecological attributes and significance of the plot observations. 		| 0..1 | No |
observationConditions | Conditions at the time of observation. | 0..1 | No |
referencePublication | Reference to an original publication and additionally a table or section within a publication. | 0..n | No |
observationGroupingID | A reference to a specific observation grouping by ID.   | 0..n | No |

### Element *taxonNameUsageConcept*

Taxon name usage concepts are identified by their element *authorName*.

Sub-element               | Description                                        |  R  |
------------------------- | -------------------------------------------------- | --- |
authorName               | A string representing a taxon name that the author of the dataset used to refer to a taxon observed within the plot.       | Yes |

### Element *method*

An element *method* provides the definition of a specific method followed in the creation of the dataset (e.g. the measurement of pH, the estimation of plant abundance or the definition of strata). From the perspective of the **VegX package** user, methods are identified uniquely through their element *name*. An important sub-element of a *method* is its *subject*, which contains the description of an attribute class to which the method applies, and is used for combining values which may be initially obtained using different methods. All attributes pointing to a given *method* are assumed to apply to the same *subject*. 

Sub-element               | Description                                        |  #  |  R  |
------------------------- | -------------------------------------------------- | --- | --- |
name               | Name associated with the method. For example, "percent cover". | 1 | Yes |
description | A full description of the type of method e.g., measured parameter or basal area of all stems > 10 cm dbh or counts of all saplings >1.35 m tall and less than 2 cm dbh. | 1 | Yes |
subject | The description of an attribute class for comparative purposes. If two methods measure the same attribute (e.g. plant cover), but with different degrees of precision and accuracy, setting 'subject' to 'plant cover' allows combining their values. All attributes pointing to the same method are assumed to apply to the same subject. | 1 | Yes |
protocolID | A reference to a specific protocol by its ID. | 0..1 | No |
citationID | A reference to a specific citation of literature. | 0..1 | No |
citationString | A string indicating the citation reference | 0..1 | Yes |

### Element *attribute*

An *attribute* element contains the definition of a specific measured property. An attribute has to be one of three types: *qualitative* (unordered categorical variable, i.e. nominal), *ordinal* (ordered list of values) or *quantitative* (a numerical variable, either discrete or continuous. The sub-elements of attributes depend on its type.

Sub-element (qualitative) | Description                                        |  #  |  R  |
------------------------- | -------------------------------------------------- | --- | --- |
methodID               | A reference to a specific method that describes the context for the qualitative code. | 1 | Yes |
code | The label of the category used for measurement values. | 1 | Yes | 
definition | Longer description of the definition of the category. | 0..1 | No |

Sub-element (ordinal)     | Description                                        |  #  |  R  |
------------------------- | -------------------------------------------------- | --- | --- |
methodID               | A reference to a method that describes the context for the ordinal code. | 1 | Yes |
code | Ordinal class code (e.g. a value like "+" or "1" in Braun-Blanquet cover scale) | 1 | Yes | 
definition | Longer description of the definition of the ordinal class. For example, ">1-5 % percent cover" for code "1" in an ordinal cover scale. | 0..1 | No |
lowerLimit | Lower limit of the ordinal class in an associated quantitative scale (e.g. 10% cover in a cover class) | 0..1 | Yes |
upperLimit | Upper limit of the ordinal class in an associated quantitative scale (e.g. 25% cover in a cover class) | 0..1 | Yes |
order | Explicit order in the sequence of ordinal values to which this class belongs. | 0..1 | Yes |

Sub-element (quantitative) | Description                                        |  #  |  R  |
-------------------------- | -------------------------------------------------- | --- | --- |
methodID               | A reference to a specific method that describes the context for the quantitative attribute. | 1 | Yes |
unit | Unit of measurement (e.g. mm, cm, square meters, number of individuals). | 1 | Yes | 
precision | The smallest place value to which the measurement is expressed (eg, if pi is represented as 3.14, then its precision is .01). | 0..1 | No |
lowerLimit | Potential lower limit of the measurement | 0..1 | Yes |
upperLimit | Potential upper limit of the measurement | 0..1 | Yes |

### Element *stratum*

The definition of a stratum, not the observation of a stratum. An individual stratum usually belongs to a ordered list that together are the set of strata definitions in use within a specific dataset. This set of strata will normally have been defined according to the same method, but individual stratum may also be assigned a method. Strata that are defined from limits in a quantitative measurement, like height, the user of the Veg-X standard can use the method pointed by *methodID* to describe the quantitative attribute associated to the stratum definition (e.g. height in m). From the perspective of the **VegX package** user, strata are uniquely identified by *stratumName*.

Sub-element (quantitative) | Description                                        |  #  |  R  |
-------------------------- | -------------------------------------------------- | --- | --- |
stratumName                | Name associated with this stratum and which identifies it. | 1 | Yes |
methodID                   | A reference to a specific method used to define this stratum. | 0..1 | Yes |
definition                 | A longer description of the stratum definition. | 0..1 | No |
order                      | An indication of a position in an ordered sequence of strata.  | 0..1 | Yes |
lowerLimit | Lower limit of the stratum in some known dimension (e.g. height) defined in the attribute of the method pointed to by 'methodID'. | 0..1 | Yes |
upperLimit | Upper limit of the stratum in some known dimension (e.g. height) defined in the attribute of the method pointed to by 'methodID'. | 0..1 | Yes |

### Element *stratumObservation*

A *stratumObservation* is a specific observation applying to a stratum in a single plot during a single date-time period. Each stratum observation may be referenced by observations of taxa or individuals within a plot. For example, abundance estimates of a taxa on a plot within a specific stratum. In addition, the *stratumObservation* may contain measurements of the lower and upper vertical limits of the stratum (if those are not fixed by the stratum definition) and an assessment of plant abundance like cover or number of individuals. A *stratumObservation* always contains a reference to a *plotObservation*, where contextual information lies (plot, project, parties, date-time period). It also contains a reference to a *stratum*, which contains its definition. From the perspective of the **VegX package** user, stratum observations are identified by *stratumID* (i.e., stratum name) and *plotObservationID* (i.e. plot name and observation start date).

Sub-element               | Description                                        |  #  |  R  |
------------------------- | -------------------------------------------------- | --- | --- |
stratumID                | A reference to a specific stratum by ID. | 1 | Yes |
plotObservationID        | A reference to a specific plotObservation. | 1 | Yes |
lowerLimitMeasurement    | A measurement of the lower limit (i.e. height) of the stratum.  | 0..1 | No |
upperLimitMeasurement    | A measurement of the upper limit (i.e. height) of the stratum.  | 0..1 | No |
stratumMeasurement       | A measurement (e.g. plant cover, or individual count) made in the stratum. | 0..n | No |
observationGroupingID | A reference to a specific observation grouping by ID.   | 0..n | No |

### Element *aggregateOrganismObservation*

An *aggregateOrganismObservation* is an observation applying to all occurrences of an organism (e.g. a taxon). An *aggregateOrganismObservation* contains a reference to a single *plotObservation* and a link to a *taxonNameUsageConceptID*, which can be linked to all the taxon identification information. Optionally, it may also link to a *stratumObservation*. It may contain one of several sub-elements *aggregateMeasurement*, each of them being an assessment of the overall occurrence of an organism in a Plot (e.g. number of stems, percentage cover, total biomass, basal area). If there is no instance of *aggregateMeasurement*, then the taxon is understood to be simply present.  From the perspective of the **VegX package** user, aggregate organism observations are uniquely identified by *plotObservationID* (i.e. plot name and observation start date) and *taxonNameUsageConceptID* (i.e. by a taxon name) and by *stratumObservationID* (i.e. stratum name) when defined.

Sub-element               | Description                                        |  #  |  R  |
------------------------- | -------------------------------------------------- | --- | --- |
plotID                   | A reference to a specific plot by ID. | 1 | Yes |
taxonNameUsageConceptID  | A reference to a specific taxonNameUsageConcept representing a taxon occurrence by ID. | 1 | Yes |
aggregateMeasurement     | A measurement for a aggregate organism value (e.g. plant cover of a taxon). Values can be further defined uppervalue, accuracy etc. Many measurements (e.g. counts, cover, basal area...) can be added to the same aggregate organism observation.  | 0..n | Yes |
stratumObservationID     | A reference to a specific stratumObservation by ID. It applies to all aggregate measurements included in this aggregateOrganismObservation. | 0..1 | Yes |
heightMeasurement        | Optional height at which the aggregated observation was made, e.g. in meters. It applies to all aggregate measurements included in this aggregateOrganismObservation. | 0..1 | No |
observationGroupingID    | A reference to a specific observation grouping by ID.   | 0..n | No |



### Element *individualOrganism*

Individual organisms are identified by *plotID* and *identificationLabel*.

Sub-element               | Description                                        |  R  |
------------------------- | -------------------------------------------------- | --- |
plotID                   | A reference to a specific plot. | Yes |
identificationLabel      | A label that is associated with an individual (e.g. a numerical tree tag). | Yes |
taxonNameUsageConceptID  | A reference to a specific taxonNameUsageConcept representing a taxon occurrence. | Yes |
birthDate | TO BE DONE | No |
relatedIndividual | An item may be related or connected in some way to other items. For example fused stems, epiphytic relationships or mapped individuals. | No |
relativePosition | Relative position of organism described in geometric space within the plot the organism is located in. Relative to the plot point of origin. | No |


### Element *individualOrganismObservation*

Individual organism observations are identified by *plotObservationID* and *individualOrganismID*.

Sub-element               | Description                                        |  R  |
------------------------- | -------------------------------------------------- | --- |
plotObservationID        | A reference to a specific plotObservation. | Yes |
individualOrganismID     | A reference to a specific individualOrganism. | Yes |
stratumObservationID     | A reference to a specific stratum observation that this individual was measured in on the plot. | Yes |
diameterBaseDistance     | A container for diameter measurements at a given distance along the stem from the ground. | Yes |
height     | TO BE DONE | No |
canopyVolume     | TO BE DONE | No |
multipleMeasurement | A n-tuple of a related measurements (e.g. paired data such as length, width and height to calculate volume). The definition of the relationship type is left open to the user, but is intended to allow specifying a set of measurements that have to be considered together.  | No |
individualOrganismHealth | Health of the individual organism referenced in this individual organism observation record. Usually used to describe dead stems. | No |

### Element *siteObservation*

A *siteObservation* is a container for all the site (i.e. soil, climate, landuse, habitat, ...) measurements made on a single plot during a single date-time period. Unlike other observation elements, it relates to *plotObservation* in a one-to-one relationship. The reason is because, unlike other entities, there is a single entity (i.e. the site) to which all measurements refer. There is no specific variable to identify uniquely site observations, but they are uniquely identified by their related *plotObservationID* (i.e. the combination of plot name and observation start date). Abiotic (i.e. soil, climate or water mass) measurements are a special kind of measurements within the Veg-X schema, in the sense that: (1) they can have IDs and can thus be related to each other: (2) and they can have relative coordinates of the measurement within the plot, in the same way as individuals.

Sub-element               | Description                                        |  #  |  R  |
------------------------- | -------------------------------------------------- | --- | --- |
plotObservationID        | A reference to a specific plotObservation. | 1 | Yes |
soilMeasurement           | A measurement of a soil attribute (soil chemistry, soil texture, structure, ...). |  0..n | Yes
climateMeasurement        | A measurement of a climate attribute. | 0..n | Yes |
waterMassMeasurement        | A measurement of an attributes of a water mass within the plot (e.g. water level, not for soil water, which should be included in soilMeasurement). | 0..n | Yes |
soilType | A specific soil type, applying to this plot during the plot observation. | 0..n | Yes |
humusType | A specific humus type, applying to this plot during the plot observation. | 0..n | Yes |
climateType | A specific climate type, applying to this plot during the plot observation. | 0..n | Yes |
hydrologicRegimeType | Reflection of frequency and duration of water level variations, applying to this plot during the plot observation. | 0..n | Yes |
legalProtection | Legal protection status of the plot during the plot observation. Recommended that this is from a closed list of legal protection status types. | 0..1 | No |
landuse        | A specific land use type, for example pasture, applying to this plot during the plot observation. | 0..n | No |
habitat        | A specific habitat type, applying to this plot during the plot observation. | 0..n | No |
observationGroupingID | A reference to a specific observation grouping by ID.   | 0..n | No |


### Element **observationGrouping**

A specific grouping of observation records, of any kind, that are grouped in the data management system owing to some common characteristic. For example, records that represent revisits to the same area for monitoring purposes can be linked together through this entity. Note that some specific groupings are already defined in the schema and therefore they should not be repeated (e.g. the grouping of observations made on a specific plot during a specific time is a plotObservation).
